import { COINS_PER_SESSION, STUDENT_ID, type DatabaseSnapshot, type Task } from './types';

export function createInitialSnapshot(): DatabaseSnapshot {
  const subjects = {
    math: {
      id: 'math',
      name: 'Mathematics',
      chapterIds: ['math-ch1', 'math-ch2', 'math-ch3'],
    },
    science: {
      id: 'science',
      name: 'Science',
      chapterIds: ['sci-ch1', 'sci-ch2'],
    },
    history: {
      id: 'history',
      name: 'History',
      chapterIds: ['hist-ch1', 'hist-ch2'],
    },
    english: {
      id: 'english',
      name: 'English',
      chapterIds: ['eng-ch1', 'eng-ch2'],
    },
    physics: {
      id: 'physics',
      name: 'Physics',
      chapterIds: ['phy-ch1', 'phy-ch2'],
    },
    chemistry: {
      id: 'chemistry',
      name: 'Chemistry',
      chapterIds: ['chem-ch1', 'chem-ch2'],
    },
    cs: {
      id: 'cs',
      name: 'Computer Science',
      chapterIds: ['cs-ch1', 'cs-ch2'],
    },
    biology: {
      id: 'biology',
      name: 'Biology',
      chapterIds: ['bio-ch1', 'bio-ch2'],
    },
    economics: {
      id: 'economics',
      name: 'Economics',
      chapterIds: ['econ-ch1', 'econ-ch2'],
    },
    geography: {
      id: 'geography',
      name: 'Geography',
      chapterIds: ['geo-ch1', 'geo-ch2'],
    },
    art: {
      id: 'art',
      name: 'Art & Design',
      chapterIds: ['art-ch1', 'art-ch2'],
    },
  };

  const chapters = {
    'math-ch1': { id: 'math-ch1', subjectId: 'math', title: 'Algebra Basics', taskIds: ['t-m1', 't-m2', 't-m3', 't-m4', 't-m5'] },
    'math-ch2': { id: 'math-ch2', subjectId: 'math', title: 'Geometry', taskIds: ['t-m6', 't-m7', 't-m8', 't-m9'] },
    'math-ch3': { id: 'math-ch3', subjectId: 'math', title: 'Trigonometry', taskIds: ['t-m10', 't-m11', 't-m12', 't-m13'] },
    'sci-ch1': { id: 'sci-ch1', subjectId: 'science', title: 'Cells & Life', taskIds: ['t-s1', 't-s2', 't-s3', 't-s4', 't-s5'] },
    'sci-ch2': { id: 'sci-ch2', subjectId: 'science', title: 'Ecology', taskIds: ['t-s6', 't-s7', 't-s8', 't-s9'] },
    'hist-ch1': { id: 'hist-ch1', subjectId: 'history', title: 'Ancient Civilizations', taskIds: ['t-h1', 't-h2', 't-h3', 't-h4', 't-h5'] },
    'hist-ch2': { id: 'hist-ch2', subjectId: 'history', title: 'Modern World', taskIds: ['t-h6', 't-h7', 't-h8', 't-h9', 't-h10'] },
    'eng-ch1': { id: 'eng-ch1', subjectId: 'english', title: 'Poetry & Prose', taskIds: ['t-e1', 't-e2', 't-e3', 't-e4', 't-e5'] },
    'eng-ch2': { id: 'eng-ch2', subjectId: 'english', title: 'Essay Writing', taskIds: ['t-e6', 't-e7', 't-e8', 't-e9'] },
    'phy-ch1': { id: 'phy-ch1', subjectId: 'physics', title: 'Mechanics', taskIds: ['t-p1', 't-p2', 't-p3', 't-p4', 't-p5'] },
    'phy-ch2': { id: 'phy-ch2', subjectId: 'physics', title: 'Waves & Light', taskIds: ['t-p6', 't-p7', 't-p8', 't-p9'] },
    'chem-ch1': { id: 'chem-ch1', subjectId: 'chemistry', title: 'Atomic Structure', taskIds: ['t-c1', 't-c2', 't-c3', 't-c4', 't-c5'] },
    'chem-ch2': { id: 'chem-ch2', subjectId: 'chemistry', title: 'Chemical Reactions', taskIds: ['t-c6', 't-c7', 't-c8', 't-c9', 't-c10'] },
    'cs-ch1': { id: 'cs-ch1', subjectId: 'cs', title: 'Programming Fundamentals', taskIds: ['t-x1', 't-x2', 't-x3', 't-x4', 't-x5'] },
    'cs-ch2': { id: 'cs-ch2', subjectId: 'cs', title: 'Data Structures', taskIds: ['t-x6', 't-x7', 't-x8', 't-x9', 't-x10'] },
    'bio-ch1': { id: 'bio-ch1', subjectId: 'biology', title: 'Genetics', taskIds: ['t-b1', 't-b2', 't-b3', 't-b4', 't-b5'] },
    'bio-ch2': { id: 'bio-ch2', subjectId: 'biology', title: 'Human Body Systems', taskIds: ['t-b6', 't-b7', 't-b8', 't-b9'] },
    'econ-ch1': { id: 'econ-ch1', subjectId: 'economics', title: 'Microeconomics', taskIds: ['t-n1', 't-n2', 't-n3', 't-n4', 't-n5'] },
    'econ-ch2': { id: 'econ-ch2', subjectId: 'economics', title: 'Macroeconomics', taskIds: ['t-n6', 't-n7', 't-n8', 't-n9'] },
    'geo-ch1': { id: 'geo-ch1', subjectId: 'geography', title: 'Physical Geography', taskIds: ['t-g1', 't-g2', 't-g3', 't-g4', 't-g5'] },
    'geo-ch2': { id: 'geo-ch2', subjectId: 'geography', title: 'Human Geography', taskIds: ['t-g6', 't-g7', 't-g8', 't-g9', 't-g10'] },
    'art-ch1': { id: 'art-ch1', subjectId: 'art', title: 'Drawing Fundamentals', taskIds: ['t-a1', 't-a2', 't-a3', 't-a4', 't-a5'] },
    'art-ch2': { id: 'art-ch2', subjectId: 'art', title: 'Color & Composition', taskIds: ['t-a6', 't-a7', 't-a8', 't-a9'] },
  };

  const tasks: Record<string, Task> = {
    't-m1': makeTask('t-m1', 'math-ch1', 'Linear equations intro'),
    't-m2': makeTask('t-m2', 'math-ch1', 'Solving for x'),
    't-m3': makeTask('t-m3', 'math-ch1', 'Practice set A'),
    't-m4': makeTask('t-m4', 'math-ch1', 'Word problems'),
    't-m5': makeTask('t-m5', 'math-ch1', 'Algebra quiz prep'),
    't-m6': makeTask('t-m6', 'math-ch2', 'Angles & triangles'),
    't-m7': makeTask('t-m7', 'math-ch2', 'Pythagorean theorem'),
    't-m8': makeTask('t-m8', 'math-ch2', 'Circles & arcs'),
    't-m9': makeTask('t-m9', 'math-ch2', 'Coordinate geometry'),
    't-m10': makeTask('t-m10', 'math-ch3', 'Sine & cosine basics'),
    't-m11': makeTask('t-m11', 'math-ch3', 'Unit circle'),
    't-m12': makeTask('t-m12', 'math-ch3', 'Trig identities'),
    't-m13': makeTask('t-m13', 'math-ch3', 'Applied trig problems'),
    't-s1': makeTask('t-s1', 'sci-ch1', 'Cell structure'),
    't-s2': makeTask('t-s2', 'sci-ch1', 'Organelles overview'),
    't-s3': makeTask('t-s3', 'sci-ch1', 'Cell division'),
    't-s4': makeTask('t-s4', 'sci-ch1', 'Lab: microscope skills'),
    't-s5': makeTask('t-s5', 'sci-ch1', 'Organelles quiz'),
    't-s6': makeTask('t-s6', 'sci-ch2', 'Ecosystems intro'),
    't-s7': makeTask('t-s7', 'sci-ch2', 'Food chains & webs'),
    't-s8': makeTask('t-s8', 'sci-ch2', 'Biomes of the world'),
    't-s9': makeTask('t-s9', 'sci-ch2', 'Conservation case study'),
    't-h1': makeTask('t-h1', 'hist-ch1', 'Mesopotamia & Egypt'),
    't-h2': makeTask('t-h2', 'hist-ch1', 'Indus Valley civilization'),
    't-h3': makeTask('t-h3', 'hist-ch1', 'Greek city-states'),
    't-h4': makeTask('t-h4', 'hist-ch1', 'Roman Republic'),
    't-h5': makeTask('t-h5', 'hist-ch1', 'Primary source analysis'),
    't-h6': makeTask('t-h6', 'hist-ch2', 'Industrial Revolution'),
    't-h7': makeTask('t-h7', 'hist-ch2', 'World War I causes'),
    't-h8': makeTask('t-h8', 'hist-ch2', 'Cold War overview'),
    't-h9': makeTask('t-h9', 'hist-ch2', 'Decolonization movements'),
    't-h10': makeTask('t-h10', 'hist-ch2', 'Timeline project'),
    't-e1': makeTask('t-e1', 'eng-ch1', 'Sonnet structure'),
    't-e2': makeTask('t-e2', 'eng-ch1', 'Metaphor & imagery'),
    't-e3': makeTask('t-e3', 'eng-ch1', 'Short story elements'),
    't-e4': makeTask('t-e4', 'eng-ch1', 'Character analysis'),
    't-e5': makeTask('t-e5', 'eng-ch1', 'Poetry recitation prep'),
    't-e6': makeTask('t-e6', 'eng-ch2', 'Thesis statements'),
    't-e7': makeTask('t-e7', 'eng-ch2', 'Body paragraphs'),
    't-e8': makeTask('t-e8', 'eng-ch2', 'Evidence & citations'),
    't-e9': makeTask('t-e9', 'eng-ch2', 'Draft peer review'),
    't-p1': makeTask('t-p1', 'phy-ch1', 'Motion & displacement'),
    't-p2': makeTask('t-p2', 'phy-ch1', 'Velocity-time graphs'),
    't-p3': makeTask('t-p3', 'phy-ch1', "Newton's laws"),
    't-p4': makeTask('t-p4', 'phy-ch1', 'Friction & forces'),
    't-p5': makeTask('t-p5', 'phy-ch1', 'Mechanics problem set'),
    't-p6': makeTask('t-p6', 'phy-ch2', 'Wave properties'),
    't-p7': makeTask('t-p7', 'phy-ch2', 'Sound & frequency'),
    't-p8': makeTask('t-p8', 'phy-ch2', 'Reflection & refraction'),
    't-p9': makeTask('t-p9', 'phy-ch2', 'Optics lab report'),
    't-c1': makeTask('t-c1', 'chem-ch1', 'Protons, neutrons, electrons'),
    't-c2': makeTask('t-c2', 'chem-ch1', 'Periodic table trends'),
    't-c3': makeTask('t-c3', 'chem-ch1', 'Electron configuration'),
    't-c4': makeTask('t-c4', 'chem-ch1', 'Isotopes'),
    't-c5': makeTask('t-c5', 'chem-ch1', 'Atomic structure quiz'),
    't-c6': makeTask('t-c6', 'chem-ch2', 'Balancing equations'),
    't-c7': makeTask('t-c7', 'chem-ch2', 'Types of reactions'),
    't-c8': makeTask('t-c8', 'chem-ch2', 'Stoichiometry basics'),
    't-c9': makeTask('t-c9', 'chem-ch2', 'Acids & bases intro'),
    't-c10': makeTask('t-c10', 'chem-ch2', 'Lab safety & procedure'),
    't-x1': makeTask('t-x1', 'cs-ch1', 'Variables & data types'),
    't-x2': makeTask('t-x2', 'cs-ch1', 'Conditionals'),
    't-x3': makeTask('t-x3', 'cs-ch1', 'Loops & iteration'),
    't-x4': makeTask('t-x4', 'cs-ch1', 'Functions'),
    't-x5': makeTask('t-x5', 'cs-ch1', 'Debugging exercises'),
    't-x6': makeTask('t-x6', 'cs-ch2', 'Arrays & lists'),
    't-x7': makeTask('t-x7', 'cs-ch2', 'Stacks & queues'),
    't-x8': makeTask('t-x8', 'cs-ch2', 'Hash maps'),
    't-x9': makeTask('t-x9', 'cs-ch2', 'Big-O intuition'),
    't-x10': makeTask('t-x10', 'cs-ch2', 'Implementation project'),
    't-b1': makeTask('t-b1', 'bio-ch1', 'DNA structure'),
    't-b2': makeTask('t-b2', 'bio-ch1', 'Mendelian inheritance'),
    't-b3': makeTask('t-b3', 'bio-ch1', 'Punnett squares'),
    't-b4': makeTask('t-b4', 'bio-ch1', 'Gene expression'),
    't-b5': makeTask('t-b5', 'bio-ch1', 'Genetics problem set'),
    't-b6': makeTask('t-b6', 'bio-ch2', 'Circulatory system'),
    't-b7': makeTask('t-b7', 'bio-ch2', 'Respiratory system'),
    't-b8': makeTask('t-b8', 'bio-ch2', 'Nervous system'),
    't-b9': makeTask('t-b9', 'bio-ch2', 'Body systems quiz'),
    't-n1': makeTask('t-n1', 'econ-ch1', 'Supply & demand'),
    't-n2': makeTask('t-n2', 'econ-ch1', 'Market equilibrium'),
    't-n3': makeTask('t-n3', 'econ-ch1', 'Elasticity'),
    't-n4': makeTask('t-n4', 'econ-ch1', 'Consumer choice'),
    't-n5': makeTask('t-n5', 'econ-ch1', 'Microeconomics review'),
    't-n6': makeTask('t-n6', 'econ-ch2', 'GDP & growth'),
    't-n7': makeTask('t-n7', 'econ-ch2', 'Inflation & unemployment'),
    't-n8': makeTask('t-n8', 'econ-ch2', 'Fiscal policy'),
    't-n9': makeTask('t-n9', 'econ-ch2', 'Monetary policy'),
    't-g1': makeTask('t-g1', 'geo-ch1', 'Plate tectonics'),
    't-g2': makeTask('t-g2', 'geo-ch1', 'Climate zones'),
    't-g3': makeTask('t-g3', 'geo-ch1', 'Rivers & erosion'),
    't-g4': makeTask('t-g4', 'geo-ch1', 'Weather patterns'),
    't-g5': makeTask('t-g5', 'geo-ch1', 'Map reading skills'),
    't-g6': makeTask('t-g6', 'geo-ch2', 'Population dynamics'),
    't-g7': makeTask('t-g7', 'geo-ch2', 'Urbanization'),
    't-g8': makeTask('t-g8', 'geo-ch2', 'Migration patterns'),
    't-g9': makeTask('t-g9', 'geo-ch2', 'Cultural landscapes'),
    't-g10': makeTask('t-g10', 'geo-ch2', 'Geography case study'),
    't-a1': makeTask('t-a1', 'art-ch1', 'Line & contour drawing'),
    't-a2': makeTask('t-a2', 'art-ch1', 'Shading techniques'),
    't-a3': makeTask('t-a3', 'art-ch1', 'Perspective basics'),
    't-a4': makeTask('t-a4', 'art-ch1', 'Still life sketch'),
    't-a5': makeTask('t-a5', 'art-ch1', 'Portfolio piece 1'),
    't-a6': makeTask('t-a6', 'art-ch2', 'Color wheel theory'),
    't-a7': makeTask('t-a7', 'art-ch2', 'Warm & cool palettes'),
    't-a8': makeTask('t-a8', 'art-ch2', 'Rule of thirds'),
    't-a9': makeTask('t-a9', 'art-ch2', 'Final composition'),
  };

  return {
    version: 0,
    mutations: {},
    tasks,
    chapters,
    subjects,
    focusSessions: {},
    student: {
      studentId: STUDENT_ID,
      coins: 0,
      streakDays: 0,
      lastSuccessDate: null,
      todayFocusMinutes: 0,
      todayFocusDate: null,
    },
    processedSessionRewards: {},
    n8nNotificationsSent: {},
    notificationLog: [],
  };
}

function makeTask(id: string, chapterId: string, title: string) {
  return {
    id,
    chapterId,
    title,
    status: 'not_started' as const,
    deleted: false,
    lamport: 0,
    updatedByDeviceId: 'server',
  };
}

export { COINS_PER_SESSION };
